---
title: "431 Assignment 5 Grading Rubric"
author: "431 Staff"
date: "Assignment was due at noon 2017-11-03"
linkcolor: blue
output:
  pdf_document: default
---

## We are grading all questions, for a total of 100 points.

# Question 1 (20 points)

At least 16 out of 20 points should be given if:

- the essay is clear, 
- answers the questions posed, 
- meets the word limit, and 
- has generally good grammar and spelling.

Students should receive **19-20 points** if they meet all of the standards above, and are one of the 6-10 best essays in the group.

Students should receive **16-18 points** if they meet all of the standards above, but were not in that top group.

Students should receive **13-15 points** if they meet most of the standards above

Students should receive **12 or fewer points** if they fail to meet at least two of the standards above, and a note about why they are receiving no more than 12 points should be available in the `HW5-Notes` section of the roster.

# Question 2 (10 points)

- 10 points for doing everything right
    + Using power.prop.test (4 points)
    + p1 of 0.1 and p2 of 0.05 (2 points) or vice versa
    + Power of 0.8, and significance of 0.05 (2 points)
    + Arriving at 435 patients in *each* group or a total of 870 (2 points)

# Question 3 (10 points)

- Award 10 points for:
    + Setting up the table correctly
    + Interpreting the table correctly
- Award at most 8 points for doing only one of the above
- Award at least 5 points for any reasonable attempt.

# Question 4 (10 points)

- Award 10 points for:
    + Setting up the table correctly
    + Interpreting the table correctly
- Award at most 8 points for doing only one of the above
- Award at least 5 points for any reasonable attempt.

# Question 5 (5 points)

- 3 points for identifying Coexpose 2 as the required format of data.
- 2 more points for describing the difference between wide and long format.

# Question 6 (5 points)

- 3 points for providing numerical summary by center
- 2 more points for correct ranking. 

# Question 7 (10 points)

- 7 points for making a correct graph
- 3 points for giving a correct conclusion, incluiding that there are not serious concerns in the Normality or the Constant Variance assumption.

# Question 8 (10 points)

- 5 points for comparing the means.
- 5 points for  drawing conclusion that there is a statistically detectable difference in p < 0.10, at the 90% confidence level.
- 4 pt. for a reasonable attempt


# Question 9 (10 points)

- 6 points for correct equation
- 4 more points for correct R^2^ and correct interpretation of R^2^.

# Question 10 (10 points)

- 4 points for the result of the Tukey HSD method - 4 points for the Bonferroni approach 
- 2 points for a conclusion including that Rancho Los Amigos has a statistically significantly larger mean than does Johns Hopkins.


# Class Roster Elements

The roster is available now in the same folder as the other rosters.

Column | Explanation
:---------------: | -----------------------------------------------------------------
Name, ID, etc. | Student Identifying Information 
`HW5-Q1` | Question 1 results (0-20 points)
`HW5-Top Essays` | Identify the top 6-10 Essays (Q1)
`HW5-Q2` | Question 2 results (0-10 points)
`HW5-Q3` | Question 3 results (0-10 points)
`HW5-Q4` | Question 4 results (0-10 points)
`HW5-Q5` | Question 5 results (0-5 points)
`HW5-Q6` | Question 6 results (0-5 points)
`HW5-Q7` | Question 7 results (0-10 points)
`HW5-Q8` | Question 8 results (0-10 points)
`HW5-Q9` | Question 9 results (0-10 points)
`HW5-Q10` | Question 10 results (0-10 points)
`HW5` | Total Score on Assignment 5 (0-100 points)
`HW5-Notes` | Notes from TAs to Students

